# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package to TestPyPI

on:
  push:
    branches:
      - dev
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
        shell: bash

      - name: Build the package
        run: |
          python setup.py sdist bdist_wheel
        shell: bash

      - name: Publish package to Test PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TESTPYPI_API_TOKEN }}
        run: |
          twine upload --repository-url https://test.pypi.org/legacy/ dist/*
        shell: bash

      - name: Install package and dependencies for testing
        run: |
          pip install -r requirements.txt || echo "No requirements.txt found"
          pip install .
        shell: bash

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}/betterstar
        run: |
          python -m unittest discover -s test
        shell: bash